import Header from "@/components/_header/header";
import "../globals.css";
import Categories from "@/components/_categories/categories";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={``}>
        <Header />
        <Categories />
        {children}
      </body>
    </html>
  );
}
